name: fullNelson
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#865b30'
    - '#2e1010'
    - '#c9a164'
    - '#e3c48b'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
